import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react'
import New from './new'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col w-screen h-screen bg-black justify-center items-center' >
          <p className='text-[6vmax] text-white font-extrabold' >zkPay</p>
          <p className='text-xl text-white font-thin ' >Paisa aapka, jawabdaari hamari</p>
          <div className='flex flex-col w-[40%] h-fit p-6 border-[1px] border-white rounded-2xl mt-14' >
          <Tabs>
            <TabList>
              <Tab className='text-white text-xl font-medium' >Send/Receive</Tab>
              <Tab className='text-white text-xl font-medium' >Withdraw</Tab>
            </TabList>

            <TabPanels>
              <TabPanel>
                <div className='flex flex-row w-full h-fit justify-between items-center text-white ' >
                    <Tabs size={'md'} variant={'solid-rounded'} >
                      <TabList>
                        <Tab className='text-white text-xl font-medium' >Send</Tab>
                        <Tab className='text-white text-xl font-medium' >Receive</Tab>
                      </TabList>
                      <TabPanels>
                        <TabPanel>

                        </TabPanel>
                        <TabPanel>
                          <New/>
                        </TabPanel>
                      </TabPanels>
                    </Tabs>
                </div>
              </TabPanel>
              <TabPanel>
                <p>two!</p>
              </TabPanel>
            </TabPanels>
          </Tabs>
          </div>
      </div>

      </div>
  )
}

export default Home
